import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigatorPages from "./components/navigatorPages";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="linksytal">
          <h1>Rick y Morty </h1>
          <NavigatorPages/>
          {children}
        </div>
      </body>
    </html>
  );
}
